Update ApiTestCase to be compliant with ApiPlatform v3.0
symfony/maker-bundle pull request #1015
Opened 2021-11-17 08:04 UTC by laryjulien

Following the work in progress in https://github.com/api-platform/core/pull/4556, ApiTestCase will be moved from ApiPlatform\Core\Bridge\Symfony\Bundle\Test to ApiPlatform\Symfony\Bundle\Test. The current file location will be deprecated in 2.7 and become invalid in 3.0 .

As recommended by @dunglas, this implementation is compatible with all versions of API Platform.

2021-11-17 10:07 UTC, dunglas requested changes

2021-11-17 10:07 UTC, dunglas commented on src/Maker/MakeTest.php
> +        if ('ApiTestCase' === $input->getArgument('type') && !(class_exists(ApiTestCase::class) || class_exists(LegacyApiTestCase::class))) {
```suggestion
        if ('ApiTestCase' === $input->getArgument('type') && !class_exists(ApiTestCase::class) && !class_exists(LegacyApiTestCase::class)) {
```

2021-11-17 14:06 UTC, laryjulien commented on src/Maker/MakeTest.php
> +        if ('ApiTestCase' === $input->getArgument('type') && !(class_exists(ApiTestCase::class) || class_exists(LegacyApiTestCase::class))) {
Condition has been changed

2021-11-18 13:58 UTC, weaverryan approved these changes

2021-11-18 16:32 UTC, dunglas approved these changes

2022-02-22 18:18 UTC, merged