add support to custom type hint
symfony/maker-bundle pull request #1021
Opened 2021-11-29 18:20 UTC by IndraGunawan

Fix #1002

2021-11-30 17:26 UTC, IndraGunawan commented
@weaverryan this PR was ready, i don't think the CI failure related to this PR, any suggestions?

2022-03-18 08:34 UTC, IndraGunawan commented
@jrushlow this PR is ready for review

2022-09-10 15:26 UTC, vladdnepr commented
up. cool to merge

2022-09-22 13:15 UTC, jrushlow requested changes
Sorry for the delay @IndraGunawan - I didnt dig through this too deep as I believe there are quite a few changes that have taken place since you first created the PR. If you can rebase and get us green tests, ill get this reviewed && merged.. Thanks in advance!

2022-09-22 13:15 UTC, jrushlow commented on tests/DependencyInjection/ConfigurationTest.php
> +namespace Indragunawan\ApiRateLimitBundle\Tests\DependencyInjection;
This should be in the `Symfony\Bundle\MakerBundle\Tests`... namespace

2024-01-01 15:25 UTC, closed without merging