[reset-password] Coding standards
symfony/maker-bundle pull request #1031
Opened 2021-12-02 09:05 UTC by seb-jean

Hi,
I changed the case to be like the standard coding:
https://twig.symfony.com/doc/3.x/coding_standards.html

2021-12-04 21:03 UTC, BahmanMD approved these changes

2022-02-15 16:48 UTC, jrushlow requested changes
Awesome! The changes look good, could you rebase this PR please. We've fixed a number of broken tests since you've opened the PR. Thanks in advanced.

2022-02-15 19:10 UTC, jrushlow approved these changes
Thank you @seb-jean!

2022-02-16 00:15 UTC, weaverryan commented
And thanks again @seb-jean!

2022-02-16 00:15 UTC, merged