make:entity Use the namespace instead of the full class name for MappingDriver
symfony/maker-bundle pull request #1054
Opened 2022-01-23 14:11 UTC by michaelphillpotts

This fixes #1053

2022-02-15 16:50 UTC, jrushlow requested changes
Awesome! Could you rebase this PR please. We've fixed a number of broken tests since you've opened the PR. Thanks in advanced.

2022-02-16 20:33 UTC, michaelphillpotts commented
Rebased the PR

2022-02-22 18:07 UTC, weaverryan commented on src/Doctrine/DoctrineHelper.php
> +            $classNamespace = implode('\\', $classNameComponents);
Could you add a comment about which situation this is addressing? A test would be ideal, though I don't know how easy that would be to add.

Thanks!

2022-02-28 19:55 UTC, michaelphillpotts commented
Hi

I have added a comment to the new logic.

Regarding the tests I have had a try, but not sure of where they should be placed (I was using `EntityRegeneratorTest`), the correctness of them, and how useful they are?
The test data set `mixed_config_similar_namespace` fails on current branch and passes with this pull request.

The 2 functions I came up with are:
```php
   /**
     * @dataProvider getMappingDriverTests
     */
    public function testMappingDriverSelection(string $driverClass, ?array $annotatedPrefixes, bool $doesUseMappingDriver): void
    {
        $compatUtil = $this->createMock(PhpCompatUtil::class);

        $registry = $this->createMock(ManagerRegistry::class);
        $registry->expects($this->any())
            ->method('getManagerForClass')
            ->willThrowException(new \ReflectionException());

        $helper = new DoctrineHelper('', $compatUtil, $registry, true, $annotatedPrefixes);

        $this->assertSame($doesUseMappingDriver, $helper->doesClassUseDriver('App\\Entity\\UserProfile', $driverClass),
            sprintf('DoctrineHelper confirms that App\\Entity\\UserProfile %s use the %s driver (based on provided config)', $doesUseMappingDriver ? 'does' : 'does not', $driverClass)
        );

    }

    public function getMappingDriverTests(): \Generator
    {
        yield 'empty_config' => [
            'Doctrine\\ORM\\Mapping\\Driver\\AttributeDriver',
            null,
            false,
        ];

        $hasAttributeDriver = class_exists(\Doctrine\ORM\Mapping\Driver\AttributeDriver::class);
        $hasAnnotationDriver = class_exists(\Doctrine\ORM\Mapping\Driver\AnnotationDriver::class);

        if ($hasAttributeDriver) {
            $attributeDriver = $this->createMock(\Doctrine\ORM\Mapping\Driver\AttributeDriver::class);
            yield 'basic_config_attributes' => [
                \Doctrine\ORM\Mapping\Driver\AttributeDriver::class,
                [
                    'default' => [
                        [
                            'App\\Entity',
                            $attributeDriver
                        ]
                    ]
                ],
                true,
            ];
        }

        if ($hasAnnotationDriver) {
            $annotationDriver = $this->createMock(\Doctrine\ORM\Mapping\Driver\AnnotationDriver::class);
            yield 'basic_config_annotations' => [
                \Doctrine\ORM\Mapping\Driver\AnnotationDriver::class,
                [
                    'default' => [
                        [
                            'App\\Entity',
                            $annotationDriver
                        ]
                    ]
                ],
                true,
            ];
        }

        if ($hasAttributeDriver && $hasAnnotationDriver) {
            $attributeDriver = $this->createMock(\Doctrine\ORM\Mapping\Driver\AttributeDriver::class);
            $annotationDriver = $this->createMock(\Doctrine\ORM\Mapping\Driver\AnnotationDriver::class);

            // 2 namespaces - namespaces start with different characters (A / B)
            // New class App\Entity\Profile should be using the AttributeDriver as it belongs to App\Entity namespace
            yield 'mixed_config_different_namespaces' => [
                \Doctrine\ORM\Mapping\Driver\AttributeDriver::class,
                [
                    'default' => [
                        [
                            'App\\Entity',
                            $attributeDriver
                        ],
                        [
                            'BetaCorp\Bundle\BetaBundle\Entity',
                            $annotationDriver
                        ]
                    ]
                ],
                true,
            ];

            // 2 namespaces - namespaces start with same characters (A / A)
            // New class App\Entity\Profile should be using the AttributeDriver as it belongs to App\Entity namespace
            yield 'mixed_config_similar_namespace' => [
                \Doctrine\ORM\Mapping\Driver\AttributeDriver::class,
                [
                    'default' => [
                        [
                            'App\\Entity',
                            $attributeDriver
                        ],
                        [
                            'ABC\Bundle\ABCBundle\Entity',
                            $annotationDriver
                        ]
                    ]
                ],
                true,
            ];
        }

    }

```

2022-05-04 15:22 UTC, jrushlow approved these changes
Thank you @michaelphillpotts!

2022-05-04 15:22 UTC, merged

2022-05-23 11:02 UTC, UBERPHP commented
I use PHP 8.1 and recently just got an error: "Class "Doctrine\Persistence\Mapping\Driver\AnnotationDriver" does not exist"
I guess this is related.
please see my reproduction:

```
#composer create-project symfony/website-skeleton:"^4.4" my_project_directory44
Creating a "symfony/website-skeleton:^4.4" project at "./my_project_directory44"
symfony/flex contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "symfony/flex" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
Installing symfony/website-skeleton (v4.4.99)
  - Downloading symfony/website-skeleton (v4.4.99)
  - Installing symfony/website-skeleton (v4.4.99): Extracting archive
Created project in /home/vagrant/domains/hpcismart.com.local/build-archive/0/my_project_directory44
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking symfony/flex (v1.18.7)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/flex (v1.18.7): Extracting archive
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "4.4.*"
Updating dependencies
Lock file operations: 131 installs, 0 updates, 0 removals
  - Locking doctrine/annotations (1.13.2)
  - Locking doctrine/cache (2.2.0)
  - Locking doctrine/collections (1.6.8)
  - Locking doctrine/common (3.3.0)
  - Locking doctrine/dbal (3.3.6)
  - Locking doctrine/deprecations (v1.0.0)
  - Locking doctrine/doctrine-bundle (2.6.3)
  - Locking doctrine/doctrine-migrations-bundle (3.2.2)
  - Locking doctrine/event-manager (1.1.1)
  - Locking doctrine/inflector (2.0.4)
  - Locking doctrine/instantiator (1.4.1)
  - Locking doctrine/lexer (1.2.3)
  - Locking doctrine/migrations (3.5.1)
  - Locking doctrine/orm (2.12.2)
  - Locking doctrine/persistence (3.0.2)
  - Locking doctrine/sql-formatter (1.1.2)
  - Locking egulias/email-validator (3.1.2)
  - Locking friendsofphp/proxy-manager-lts (v1.0.12)
  - Locking laminas/laminas-code (4.5.1)
  - Locking monolog/monolog (1.27.0)
  - Locking myclabs/deep-copy (1.11.0)
  - Locking nikic/php-parser (v4.13.2)
  - Locking phar-io/manifest (2.0.3)
  - Locking phar-io/version (3.2.1)
  - Locking phpdocumentor/reflection-common (2.2.0)
  - Locking phpdocumentor/reflection-docblock (5.3.0)
  - Locking phpdocumentor/type-resolver (1.6.1)
  - Locking phpspec/prophecy (v1.15.0)
  - Locking phpunit/php-code-coverage (9.2.15)
  - Locking phpunit/php-file-iterator (3.0.6)
  - Locking phpunit/php-invoker (3.1.1)
  - Locking phpunit/php-text-template (2.0.4)
  - Locking phpunit/php-timer (5.0.3)
  - Locking phpunit/phpunit (9.5.20)
  - Locking psr/cache (2.0.0)
  - Locking psr/container (1.1.2)
  - Locking psr/link (1.1.1)
  - Locking psr/log (1.1.4)
  - Locking sebastian/cli-parser (1.0.1)
  - Locking sebastian/code-unit (1.0.8)
  - Locking sebastian/code-unit-reverse-lookup (2.0.3)
  - Locking sebastian/comparator (4.0.6)
  - Locking sebastian/complexity (2.0.2)
  - Locking sebastian/diff (4.0.4)
  - Locking sebastian/environment (5.1.4)
  - Locking sebastian/exporter (4.0.4)
  - Locking sebastian/global-state (5.0.5)
  - Locking sebastian/lines-of-code (1.0.3)
  - Locking sebastian/object-enumerator (4.0.4)
  - Locking sebastian/object-reflector (2.0.4)
  - Locking sebastian/recursion-context (4.0.4)
  - Locking sebastian/resource-operations (3.0.3)
  - Locking sebastian/type (3.0.0)
  - Locking sebastian/version (3.0.2)
  - Locking sensio/framework-extra-bundle (v5.6.1)
  - Locking symfony/asset (v4.4.40)
  - Locking symfony/browser-kit (v4.4.37)
  - Locking symfony/cache (v4.4.41)
  - Locking symfony/cache-contracts (v2.5.1)
  - Locking symfony/config (v4.4.41)
  - Locking symfony/console (v4.4.41)
  - Locking symfony/css-selector (v4.4.37)
  - Locking symfony/debug (v4.4.41)
  - Locking symfony/debug-bundle (v4.4.37)
  - Locking symfony/debug-pack (v1.0.10)
  - Locking symfony/dependency-injection (v4.4.41)
  - Locking symfony/deprecation-contracts (v3.0.1)
  - Locking symfony/doctrine-bridge (v4.4.41)
  - Locking symfony/dom-crawler (v4.4.39)
  - Locking symfony/dotenv (v4.4.37)
  - Locking symfony/error-handler (v4.4.41)
  - Locking symfony/event-dispatcher (v4.4.37)
  - Locking symfony/event-dispatcher-contracts (v1.1.12)
  - Locking symfony/expression-language (v4.4.41)
  - Locking symfony/filesystem (v4.4.39)
  - Locking symfony/finder (v4.4.41)
  - Locking symfony/form (v4.4.41)
  - Locking symfony/framework-bundle (v4.4.41)
  - Locking symfony/http-client (v4.4.41)
  - Locking symfony/http-client-contracts (v2.5.1)
  - Locking symfony/http-foundation (v4.4.41)
  - Locking symfony/http-kernel (v4.4.41)
  - Locking symfony/inflector (v4.4.37)
  - Locking symfony/intl (v4.4.41)
  - Locking symfony/mailer (v4.4.41)
  - Locking symfony/maker-bundle (v1.39.0)
  - Locking symfony/mime (v4.4.41)
  - Locking symfony/monolog-bridge (v4.4.37)
  - Locking symfony/monolog-bundle (v3.8.0)
  - Locking symfony/options-resolver (v4.4.37)
  - Locking symfony/orm-pack (v2.2.0)
  - Locking symfony/phpunit-bridge (v6.0.8)
  - Locking symfony/polyfill-intl-icu (v1.25.0)
  - Locking symfony/polyfill-intl-idn (v1.25.0)
  - Locking symfony/polyfill-intl-normalizer (v1.25.0)
  - Locking symfony/polyfill-mbstring (v1.25.0)
  - Locking symfony/polyfill-php72 (v1.25.0)
  - Locking symfony/polyfill-php73 (v1.25.0)
  - Locking symfony/polyfill-php80 (v1.25.0)
  - Locking symfony/polyfill-php81 (v1.25.0)
  - Locking symfony/process (v4.4.41)
  - Locking symfony/profiler-pack (v1.0.6)
  - Locking symfony/property-access (v4.4.41)
  - Locking symfony/property-info (v4.4.40)
  - Locking symfony/proxy-manager-bridge (v4.4.39)
  - Locking symfony/routing (v4.4.41)
  - Locking symfony/security-bundle (v4.4.41)
  - Locking symfony/security-core (v4.4.41)
  - Locking symfony/security-csrf (v4.4.37)
  - Locking symfony/security-guard (v4.4.37)
  - Locking symfony/security-http (v4.4.41)
  - Locking symfony/serializer (v4.4.41)
  - Locking symfony/serializer-pack (v1.0.4)
  - Locking symfony/service-contracts (v2.5.1)
  - Locking symfony/stopwatch (v4.4.38)
  - Locking symfony/test-pack (1.0.10)
  - Locking symfony/translation (v4.4.41)
  - Locking symfony/translation-contracts (v2.5.1)
  - Locking symfony/twig-bridge (v4.4.41)
  - Locking symfony/twig-bundle (v4.4.41)
  - Locking symfony/twig-pack (v1.0.1)
  - Locking symfony/validator (v4.4.41)
  - Locking symfony/var-dumper (v4.4.41)
  - Locking symfony/var-exporter (v4.4.41)
  - Locking symfony/web-link (v4.4.37)
  - Locking symfony/web-profiler-bundle (v4.4.41)
  - Locking symfony/yaml (v4.4.37)
  - Locking theseer/tokenizer (1.2.1)
  - Locking twig/extra-bundle (v3.4.0)
  - Locking twig/twig (v3.4.1)
  - Locking webmozart/assert (1.10.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 131 installs, 0 updates, 0 removals
  - Downloading doctrine/collections (1.6.8)
  - Downloading psr/cache (2.0.0)
  - Downloading doctrine/event-manager (1.1.1)
  - Downloading doctrine/common (3.3.0)
  - Downloading doctrine/lexer (1.2.3)
  - Downloading symfony/deprecation-contracts (v3.0.1)
  - Downloading psr/container (1.1.2)
  - Downloading symfony/service-contracts (v2.5.1)
  - Downloading symfony/stopwatch (v4.4.38)
  - Downloading symfony/polyfill-php80 (v1.25.0)
  - Downloading symfony/polyfill-php73 (v1.25.0)
  - Downloading symfony/polyfill-mbstring (v1.25.0)
  - Downloading psr/log (1.1.4)
  - Downloading symfony/filesystem (v4.4.39)
  - Downloading laminas/laminas-code (4.5.1)
  - Downloading doctrine/sql-formatt [...]