Fix error when enable_authenticator_manager is not set
symfony/maker-bundle pull request #1118
Opened 2022-05-13 21:03 UTC by l-vo

Fix error when enable_authenticator_manager is not set and true is the default value (from Symfony 6)

Related to symfony/recipes#1085

2022-05-16 18:34 UTC, jrushlow requested changes
Awesome thanks for this @l-vo If you could add a couple legacy notations, we'll get this merged in!

2022-05-16 18:34 UTC, jrushlow commented on src/Maker/MakeAuthenticator.php
> +        if (interface_exists(GuardAuthenticatorInterface::class) && !($securityData['security']['enable_authenticator_manager'] ?? false)) {
```suggestion
        // @legacy - Can be removed when Symfony 5.4 support is dropped
        if (interface_exists(GuardAuthenticatorInterface::class) && !($securityData['security']['enable_authenticator_manager'] ?? false)) {
```

2022-05-16 18:34 UTC, jrushlow commented on src/Maker/MakeRegistrationForm.php
> +        if (!interface_exists(GuardAuthenticatorInterface::class) || ($securityData['security']['enable_authenticator_manager'] ?? false)) {
```suggestion
        // @legacy - Can be removed when Symfony 5.4 support is dropped
        if (!interface_exists(GuardAuthenticatorInterface::class) || ($securityData['security']['enable_authenticator_manager'] ?? false)) {
```

2022-05-16 19:09 UTC, l-vo commented
status: ready to review

2022-05-16 19:10 UTC, l-vo commented
@jrushlow legacy comments added 🙂

2022-05-16 19:11 UTC, l-vo commented
status: needs review

2022-05-17 12:45 UTC, jrushlow approved these changes
Thank you @l-vo

2022-05-17 12:45 UTC, merged