Add support for generating UUID id fields in entities
symfony/maker-bundle pull request #1329
Opened 2023-06-27 13:58 UTC by Coffee2CodeNL

Related issues: #1037 #1033 #745

2023-08-06 15:08 UTC, flkasper commented
Suggestion for improving this PR:

- https://github.com/symfony/maker-bundle/blob/79c710ba27a38e6e0986e0c6524db3f3f345bb86/src/Maker/MakeEntity.php#L380 If uuid enabled, then uuid instead of integer

2023-08-06 15:10 UTC, Coffee2CodeNL commented
@flkasper good idea

2023-08-06 15:16 UTC, flkasper commented
Another suggestion for improvement that I had forgotten:

https://github.com/symfony/maker-bundle/blob/79c710ba27a38e6e0986e0c6524db3f3f345bb86/src/DependencyInjection/Configuration.php#L17

New project based config in config/packages/dev/maker.yaml `entity.uuid_ids: boolean` to globally enable uuid generation in the project and evaluate it in make:entity.

2024-02-16 14:19 UTC, jrushlow requested changes
This looks pretty good @Coffee2CodeNL! I have not looked to closely at the tests yet, if you can `rebase` this PR - we can work on getting those tests green! Thanks in advance...

2024-02-16 14:19 UTC, jrushlow commented on src/Doctrine/EntityClassGenerator.php
> +        if ($useUUIDIdentifier) {
Perhaps `$useUid` instead of `$useUUID` as I would assume uuid or ulid's would both be possible.

2024-02-16 14:19 UTC, jrushlow commented on src/Maker/MakeUser.php
> +        if ($input->getOption('uuid_id')) {
Let's move this conditional to the `interact` method - it's a better dx when we know right away if we're missing a key package.

2024-03-22 05:59 UTC, merged