add single_text widget for all date types
symfony/maker-bundle pull request #1393
Opened 2023-11-07 11:03 UTC by tacman

Because there are many date types, I used to the helper to get the mapping and checked for those.

2024-02-20 12:49 UTC, jrushlow requested changes
This looks good @tacman! Thank you.. Can you rebase this please and we'll get it merged in.

2024-02-20 12:54 UTC, tacman commented
A bit embarrassing, but I don't know how to do a rebase.  What do I need to do?

2024-02-20 13:09 UTC, jrushlow commented
No worries.. You should see me hunt for my post its when trying to remember how to add commits to someone else's pr

Assuming locally your remotes look something like:
```
$>  git remote -v
origin      jrushlow/maker-bundle (fetch)
origin	jrushlow/maker-bundle (push)
upstream	symfony/maker-bundle.git (fetch)
upstream	symfony/maker-bundle.git (push)
```

1) `git checkout -b feature/something main` 
2) do some work - add a few commits - fix a few tests....
3) `git fetch upstream` - the grabs all of the changes / releases / etc from `symfony/maker-bundle`
4) `git rebase upstream/main` - this tells git to rebase any changes onto your `feature/something` branch from the `symfony/maker-bundle` `main` branch.

You may encounter an error or 2 that say hey! you need to fix a conflict. If you're using PHPStorm - i recommend fixing them in there. Otherwise you'll be diving into `diff`'s that were generated by `git` in the files it mentions in the output. 

After you resolve any conflicts -> `git rebase continue` it will eventually tell you something like `fatal: No rebase in progress?` That means you're good to go.

5) `git push` odds are this will fail if you have actually rebased any changes.. you'll need to use `git push --force`.

double check the git log _before_ adding the `--force` flag.. for the most in a fork, this won't cause alot of headaches if you accidentally erase history on your pr.. but imagine if you did that to something like `tacman/super-important-project-repo` on the `main` branch.... ouch!

Further reading: https://symfony.com/doc/current/contributing/code/pull_requests.html#work-on-your-pull-request

2024-02-27 15:24 UTC, jrushlow approved these changes

2024-02-27 15:24 UTC, merged