handle property type for custom doctrine type
symfony/maker-bundle pull request #1413
Opened 2024-01-01 16:45 UTC by IndraGunawan

2024-01-01 16:57 UTC, IndraGunawan commented
CI error was not related

2024-02-26 16:13 UTC, IndraGunawan commented
@jrushlow @weaverryan any chance to review this?

2024-02-27 14:59 UTC, jrushlow requested changes
This looks good. A couple minor comments to improve readability.

2024-02-27 14:59 UTC, jrushlow commented on src/Doctrine/DoctrineHelper.php
> +            $reflection = new \ReflectionClass(\get_class(Type::getTypeRegistry()->get($columnType)));
```suggestion
            $reflection = new \ReflectionClass(($registry->get($columnType))::class);
```

2024-02-27 14:59 UTC, jrushlow commented on src/Doctrine/DoctrineHelper.php
> +        if (null === $propertyType && Type::getTypeRegistry()->has($columnType)) {
Lets exit early to avoid a bunch of nested conditionals

2024-02-27 14:59 UTC, jrushlow commented on src/Doctrine/DoctrineHelper.php
> +            if ($reflection->hasMethod('convertToPHPValue') && $returnType = $reflection->getMethod('convertToPHPValue')->getReturnType()) {
We should be able to drop this conditional all together. `getType()` always returns a `Type` and abstract `Type` has the convert method.

https://github.com/doctrine/dbal/blob/f3defbb4f88a7472314746f122f6d4d84615d424/src/Types/TypeRegistry.php#L41

2024-02-27 14:59 UTC, jrushlow commented on src/Doctrine/DoctrineHelper.php
> +                }
We could do something like `return $returnType->isBuitin() ? $returnType->getName() : ......`

2024-03-04 06:12 UTC, jrushlow approved these changes
Thank you @IndraGunawan!

2024-03-04 06:13 UTC, merged