[make:entity] Use `const` for `ASC` in ORDER BY
symfony/maker-bundle pull request #1451
Opened 2024-02-15 21:38 UTC by ThomasLandauer

2024-02-16 13:01 UTC, jrushlow requested changes

2024-02-16 13:01 UTC, jrushlow commented on src/Resources/skeleton/doctrine/Repository.tpl.php
> +//            ->orderBy('<?= $entity_alias; ?>.id', Criteria::ASC)
in general terms, I'm not opposed to using a `const` or `enum` in place of strings. My only concern would be, are `doctrine/common` / `doctrine/common/collections` classes on the chopping block in `dbal` 4||5. E.g. where we would have to revert this behavior in the immediate future.

 I took a quick peak in `dbal/src/QueryBuilder` and did not see any evidence of such a possibility. But did not dig through either of the repos for open prs/issues on the matter.

If that's not an issue, green tests - I'm all for it.

2024-02-18 16:27 UTC, ThomasLandauer commented
Using strings there is about to get deprecated, in favor of a new enum, see https://github.com/doctrine/collections/pull/389
So I'm closing here for now - I'll come up with a new PR once Doctrine has released it.
The main question here will then be: In which version should the switch be done?

2024-02-18 16:27 UTC, closed without merging

2024-02-18 16:32 UTC, jrushlow commented
Awesome! In the new PR - we'd have todo some sort of conditional to support the old strings `if(!exists(DoctrineEnum))` Looking forward to the upcoming changes.