Add new make:webhook command
symfony/maker-bundle pull request #1491
Opened 2024-03-25 10:29 UTC by maelanleborgne

Add a maker that would help create a webhook :
- Create a RequestParser extending `AbstractRequestParser` and interactively define the RequestMatcher(s) to use.
- Create a WebHookHandler implementing `ConsumerInterface` with the `#[AsRemoteEventConsumer]` attribute.
- Add an entry to config/packages/webhook.yaml with the name of the webhook + the RequestParser service name + empty secret with an instruction on how to set it (as a comment).

That is quite an easy scaffolding command but since Webhook is quite a recent component and the documentation is pretty scarce right now, I think it would make sense to have a maker to help setting things up.

![image](https://github.com/symfony/maker-bundle/assets/11990607/49c5b75a-6765-43dd-9158-e1dc12cf3e3e)

2024-03-27 14:09 UTC, jrushlow requested changes
This is looking pretty nifty @maelanleborgne - a few suggestions and I think we'll be in good shape..

2024-03-27 14:09 UTC, jrushlow commented on src/Maker/MakeWebhook.php
> +        } else {
If we can eliminate this `else` that would be awesome. Something like 
```php
$yamlConfig = YamlDump([.......])
if ($this->fileManager...... {
    $yamlConfig = .....
```

2024-03-27 14:09 UTC, jrushlow commented on src/Maker/MakeWebhook.php
> +        $this->ysm = new YamlSourceManipulator($yamlConfig);
Are we calling `$this->ysm` outside of this method? If not, let's remove the class property and keep this a local variable

2024-03-27 14:09 UTC, jrushlow commented on src/Maker/MakeWebhook.php
> +                return null;
Do the same for other parts of this maker: Let's add so more spacing within the code. grouping multiple single line variable declarations is A-OK. But using that enter button between multi-line declarations, conditionals, etc... improves readability..

```suggestion
            $choices = array_diff($availableMatchers, $addedMatchers);
            $question = new ChoiceQuestion($questionText, array_values(['<skip>'] + $choices), 0);
            $matcherName = $io->askQuestion($question);
            
            if ('<skip>' === $matcherName) {
                return null;
```

2024-03-28 09:48 UTC, maelanleborgne commented
> This is looking pretty nifty @maelanleborgne - a few suggestions and I think we'll be in good shape..

Thank you for the review. I'm at SFlive right now, I'll try to push the changes on my way back. Just curious about the bit on unit testing the regex : testing invalid cases seems pretty hard with the MakerTestCase, should I make the method public? Use reflection method and invoke maybe?

2024-03-28 12:35 UTC, jrushlow commented
The regex test can be added to: 

https://github.com/symfony/maker-bundle/blob/74a8918c15ea2ce6fe5b5233e0b46eb57745e213/tests/RegexTest.php#L17

I'll have to do some minor refactoring on that class to make it "multi-purpose" (ill get a pr up and merged here shortly) - but you should be able to add another dataProvider to that test and be all set. 

As to the regex itself - move the regex string to a constant like:
https://github.com/symfony/maker-bundle/blob/74a8918c15ea2ce6fe5b5233e0b46eb57745e213/src/Test/MakerTestEnvironment.php#L25

Then you can call that regex expression from within the class and within the test without too much trouble.

2024-04-06 14:41 UTC, jrushlow approved these changes
Awesome! Thank you @maelanleborgne

2024-04-06 14:42 UTC, merged