[make:entity] managing keyword prefixes (is, has) for boolean properties getters
symfony/maker-bundle pull request #1493
Opened 2024-03-26 18:27 UTC by ClemRiviere

- Refactoring the getter prefixes  for `make:entity`
- Introducing exceptions for boolean fields : not adding the prefix to getter name if field begins with "is" or "has"

Related to #1492

2024-03-27 10:16 UTC, nicolas-grekas reviewed
This change makes sense to me. It's consistent with the autodetection of the type (boolean) when asking for the type.
I'd suggest doing the same for setters, but only for the "is" prefix: isInternational property => setInternational. (but hasColor => setHasColor)

2024-03-27 10:16 UTC, nicolas-grekas commented on src/Util/ClassSourceManipulator.php
> +    private function getGetterName($propertyName, $returnType): ?string
```suggestion
    private function getGetterName($propertyName, $returnType): string
```

2024-03-27 13:34 UTC, jrushlow requested changes
This looks pretty good @ClemRiviere! - 1 minor comment. Also if you're up for doing the same for `addSetter()` as @nicolas-grekas suggested, that would be even more awesome!

2024-03-27 13:34 UTC, jrushlow commented on src/Util/ClassSourceManipulator.php
> +    private function getGetterName($propertyName, $returnType): ?string
`$propertyName` should by typed with `string`. And as @nicolas-grekas suggested, the return type should not be `null`able

`$returnType` can be left without a type - adding a type is out of scope in this PR (requires changes elsewhere)

2024-03-27 21:45 UTC, jrushlow approved these changes
Thanks @ClemRiviere!

2024-03-27 21:46 UTC, merged

2024-06-19 16:37 UTC, stof commented
This change does not make sense to me as it makes those setter incompatible with the property-access component (and so with the form component that relies on it)

2024-06-20 09:53 UTC, toby-griffiths commented
A link wasn't added automatically (maybe becaues it was a discussion, not an issue), but this is now causing property access issues as discussed in https://github.com/symfony/symfony/discussions/54885#discussioncomment-9814172.

2024-06-20 10:34 UTC, ClemRiviere commented
@stof I understand, I think we have two potential solutions for this : 
- rollback my work on setters so `isInternational` property becomes `isInternational()` getter and `setIsInternational(bool $isInternational)` setter in maker-bundle
- adapt property-access component to manage `is` and `has` prefixes

I would personally go for the first solution, @jrushlow or @nicolas-grekas do you guys have any advices on this topic ?