[make:schedule] Add transport name for attribute
symfony/maker-bundle pull request #1568
Opened 2024-06-01 09:51 UTC by NicolasJourdan

Hey ! 👋 

I often use the command `make:schedule` and I wanted to add this new feature : Ask for the `name` used in the attribute `#[AsSchedule]`. 

## Without name 
Console : 
<img width="828" alt="Capture d’écran 2024-06-01 à 11 49 48" src="https://github.com/symfony/maker-bundle/assets/17028390/844f16f8-6249-444e-8bba-d0d6ba508476">

Generated class : 

```php
<?php

namespace App\Scheduler;

use Symfony\Component\Scheduler\Attribute\AsSchedule;
use Symfony\Component\Scheduler\RecurringMessage;
use Symfony\Component\Scheduler\Schedule;
use Symfony\Component\Scheduler\ScheduleProviderInterface;
use Symfony\Contracts\Cache\CacheInterface;

#[AsSchedule]
final class MainSchedule implements ScheduleProviderInterface
{
    public function __construct(
        private CacheInterface $cache,
    ) {
    }

    public function getSchedule(): Schedule
    {
        return (new Schedule())
        ->add(
            // @TODO - Create a Message to schedule
            // RecurringMessage::every('1 hour', new App\Message\Message()),
        )
        ->stateful($this->cache)
        ;
    }
}
```

## With `dummy` name

Console : 
<img width="828" alt="Capture d’écran 2024-06-01 à 11 50 01" src="https://github.com/symfony/maker-bundle/assets/17028390/61e53391-1446-4402-9016-7bbf08743b79">

Generated class : 

```php
<?php

namespace App\Scheduler;

use Symfony\Component\Scheduler\Attribute\AsSchedule;
use Symfony\Component\Scheduler\RecurringMessage;
use Symfony\Component\Scheduler\Schedule;
use Symfony\Component\Scheduler\ScheduleProviderInterface;
use Symfony\Contracts\Cache\CacheInterface;

#[AsSchedule('dummy')]
final class MainSchedule implements ScheduleProviderInterface
{
    public function __construct(
        private CacheInterface $cache,
    ) {
    }

    public function getSchedule(): Schedule
    {
        return (new Schedule())
        ->add(
            // @TODO - Create a Message to schedule
            // RecurringMessage::every('1 hour', new App\Message\Message()),
        )
        ->stateful($this->cache)
        ;
    }
}
```

2024-06-02 16:08 UTC, mdoutreluingne approved these changes
:+1:

2024-06-04 17:41 UTC, jrushlow requested changes
Awesome! One minor comment

2024-06-04 17:41 UTC, jrushlow commented on src/Resources/skeleton/scheduler/Schedule.tpl.php
> +<?php endif ?>
```suggestion
#[AsSchedule<?php if ($has_transport_name): ?>('<?= $transport_name; ?>')<?php endif ?>]
```

2024-06-04 20:31 UTC, NicolasJourdan commented on src/Resources/skeleton/scheduler/Schedule.tpl.php
> +<?php endif ?>
Thanks ! 👌

2024-06-05 01:19 UTC, jrushlow approved these changes
Thank you @NicolasJourdan!

2024-06-05 01:19 UTC, merged