Update MakerFileLinkFormatter.php
symfony/maker-bundle pull request #740
Opened 2020-11-17 16:13 UTC by ehrlich-media

I checked https://github.com/symfony/console/tree/3.4 
The Method does not exist in any Version of "symfony/console". Why is it calling here?
$outputFormatterStyle->setHref($formatted);

Maybe not nesseary?

2020-11-17 16:15 UTC, ehrlich-media commented
See here:
https://github.com/symfony/maker-bundle/issues/625

2020-11-19 17:39 UTC, weaverryan commented
It looks like we need to check if this method exists and *only* call it if it does. So, you're right - but we shouldn't remove the call entirely, but only call it if it exists - it's used to make clickable links. I'm not sure why our tests didn't catch this problem on 3.4...

2021-01-12 17:55 UTC, jrushlow requested changes

2021-01-12 17:55 UTC, jrushlow commented on src/Util/MakerFileLinkFormatter.php
>          $outputFormatterStyle = new OutputFormatterStyle();
```suggestion
        $outputFormatterStyle = new OutputFormatterStyle();
        
        if (method_exists(OutputFormatterStyle::class, 'setHref')) {
            $outputFormatterStyle->setHref($formatted);
        }
```

2021-01-12 17:59 UTC, jrushlow commented
closes #625

2021-01-13 19:41 UTC, Superkooka approved these changes

2021-01-13 20:03 UTC, lyrixx approved these changes

2021-01-13 20:06 UTC, lyrixx commented
Thank you @ehrlich-media.

2021-01-13 20:06 UTC, merged