use attributes for API Platform when using PHP 8+
symfony/maker-bundle pull request #859
Opened 2021-04-03 14:40 UTC by dunglas

2021-04-05 12:53 UTC, jrushlow requested changes
`tests/tmp/.gitignore` has to stay :)

2021-04-05 20:04 UTC, dunglas commented
@jrushlow Oops, fixed!

2021-04-05 20:43 UTC, jrushlow approved these changes
thanks @dunglas!

2021-04-08 18:47 UTC, weaverryan commented
Thanks Kévin!

2021-04-08 18:47 UTC, merged